service: aintnorulebot

provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  memorySize: 256

functions:
  post_tweet:
    handler: handler.post_tweet
    environment:
      TWITTER_CONSUMER_KEY: ${ssm:/aintnorulebot/twitter_consumer_key}
      TWITTER_CONSUMER_SECRET: ${ssm:/aintnorulebot/twitter_consumer_secret}
      TWITTER_ACCESS_KEY: ${ssm:/aintnorulebot/twitter_access_key}
      TWITTER_ACCESS_SECRET: ${ssm:/aintnorulebot/twitter_access_secret}
    events:
      - schedule:
          rate: rate(12 hours)

plugins:
   - serverless-python-requirements

custom:
  pythonRequirements:
     dockerizePip: true

package:
  exclude:
    - venv/**
